import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/Footer';
import Header from '../components/Header';
import styles from '../styles/Home.module.scss';
import BodySectionA from '../components/BodySectionA';
import BodySectionB from '../components/BodySectionB';
import Nav from '../components/Navigation';


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Espresso web template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
				<Nav />
				<Header />
				<BodySectionA />
				<BodySectionB />
      </main>

      <footer>
				<Footer />
      </footer>
    </div>
  )
}
